remove dependency on Sub::Identify
ilmari/Devel-OverloadInfo pull request #1
Opened 2021-02-17 14:40 UTC by haarg

Sub::Util is in core and provides the function needed. When that is not
available, include an inlined PP version. It would be possible to try to
pick alternate implementations, and have dynamic prereqs. For this case,
it does not seem worth the effort.

The primary user of this dist is Moose, which has removed its dependency
on Sub::Identify.

2021-02-18 11:31 UTC, ilmari commented
> Sub::Util is in core and provides the function needed. When that is not
> available, include an inlined PP version. It would be possible to try to
> pick alternate implementations, and have dynamic prereqs. For this case,
> it does not seem worth the effort.

Why not just a hard dependency on Sub::Util? It's dual-life after all.

2021-02-18 12:20 UTC, haarg commented
Sub::Util requires XS. That doesn't matter for Moose, which is this module's primary user, but could for others.

If requiring XS is fine with you, I can adjust the PR.

2021-02-18 12:48 UTC, ilmari commented
Sub::Identify is already XS, isn't it? So it wouldn't be a regression, pure-perlness-wise.

2021-02-18 13:00 UTC, haarg commented
Sub::Identify is XS optional.

2021-03-17 12:46 UTC, ilmari requested changes

2021-03-17 12:46 UTC, ilmari commented on lib/Devel/OverloadInfo.pm
> +            ref $coderef or return;
`return unless ref $coderef;` would be more consistent with the other early returns. OTOH, `Sub::Util::subname()` throws "Not a subroutine reference" for these cases, which we might want to be consistent with.

2021-03-17 12:46 UTC, ilmari commented on lib/Devel/OverloadInfo.pm
> +        *subname = \&Sub::Util::subname;
The code still calls `sub_fullname()`, so either it needs to be installed as that, or the call needs changing.

2021-03-17 12:49 UTC, ilmari commented
> Sub::Util requires XS. That doesn't matter for Moose, which is this module's primary user, but could for others.
> 
> If requiring XS is fine with you, I can adjust the PR.

On second thought I don't mind the `B`-based fallback, as long as its behaviour is consistent with `Sub::Util`.

2021-03-17 16:03 UTC, merged